// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🔹 ANDROID (from google-services.json)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEEdHp3zKVj2VqCSZB3ZpBJLMk3AocSJU',
    appId: '1:264478029261:android:18d760e0a91187795e8084',
    messagingSenderId: '264478029261',
    projectId: 'garu-a5813',
    storageBucket: 'garu-a5813.firebasestorage.app',
  );

  /// 🔹 iOS (already correct)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnxemKwSmw-A-97Ac5ToXLzwKPsw8DfSk',
    appId: '1:264478029261:ios:4bd8d5e29556e9b95e8084',
    messagingSenderId: '264478029261',
    projectId: 'garu-a5813',
    storageBucket: 'garu-a5813.firebasestorage.app',
    iosBundleId: 'com.garu.customer',
  );
}
